# Generated by Django 5.0.4 on 2024-04-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='unit',
        ),
    ]
