# Generated by Django 5.0.4 on 2024-04-29 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pn', '0002_remove_food_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Title', models.CharField(max_length=255)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Foods_in_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Sum', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pn.food')),
                ('Unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pn.unit')),
                ('Document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pn.purchases')),
            ],
        ),
    ]
