# Generated by Django 5.0.4 on 2024-04-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pn', '0005_rename_foods_in_stock_foodsinstock_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
