# Generated by Django 5.0.4 on 2024-04-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pn', '0006_alter_dishingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsinstock',
            name='Quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
